FarmServer/config/routes.rb
FarmServer::Application.routes.draw do

  resources :element_types, :only => [:index]
  resources :elements, :only => [:index]
  resources :sessions, :only => [:create, :destroy]
  resources :plants, :only => [:index, :create]

=begin
  resources :plants do
    get 'growth_all', :on => collection
  end

  resources :picture do
    get 'download', :on => collection
  end
=end

  match 'plants/growth_all' => 'plants#growth_all'
  match 'plants/:id' => 'plants#destroy'

end

FarmServer/app/models/plant.rb
class Plant < ActiveRecord::Base
  belongs_to :field
  belongs_to :element_type
  belongs_to :growth_stage
end

FarmServer/app/controllers/plants_controller.rb
require "builder"
class PlantsController < ApplicationController
  MAX_GROWTH = 5

  # GET /plants
  def index
    begin
      render xml: generate_XMl()
    rescue Exception => exc
      render xml: error(exc)
    end
  end

  # POST /plants
  def create
    begin
      params.delete(:action)
      params.delete(:controller)
      params[:field_id] = Field.find_by_user_id(current_user.id).id

      @plant = Plant.new(params)

      if @plant.save
        doc = Builder::XmlMarkup.new(:target => out_string = "", :indent => 1)
        doc.Plant(@plant.attributes)

        render xml: out_string
      end
    rescue Exception => exc
      render xml: error(exc)
    end
  end

  #Вырастить все растения на 1 стадию
  #GET /plants/growth_all
  def growth_all
    begin
      update_count = 0
      field_id = Field.find_by_user_id(current_user.id).id
      plants = Plant.find_all_by_field_id(field_id)
      plants.each {|plant|
       if plant[:growth_stage_id] < MAX_GROWTH
         if plant.update_attributes({:growth_stage_id => plant[:growth_stage_id] + 1})
           update_count += 1
         end
       else
         update_count += 1
       end
      }

      if (update_count == plants.length)
        render xml: generate_XMl()
      end
    rescue Exception => exc
      render xml: error(exc)
    end
  end

  # DELETE /plants/1
  def destroy
    begin
      @plant = Plant.find(params[:id])
      @plant.destroy
      render xml: ok('Plant deleted successfully')
    rescue Exception => exc
      render xml: error(exc)
    end
  end

  def generate_XMl()
    begin
      field = Field.select("zero_x, zero_y, size_x, size_y").find_by_user_id(current_user.id)
      field_id = Field.find_by_user_id(current_user.id)
      plants = Plant.find_all_by_field_id(field_id)
      doc = Builder::XmlMarkup.new(:target => out_string = "", :indent => 1)
      doc.Field(field.attributes){
        plants.each{ |plant|
          doc.Plant(plant.attributes)
        }
      }
      return out_string
    rescue Exception => exc
      raise(exc)
    end
  end
end

FarmServer/app/helpers/plants_helper.rb
module PlantsHelper
end

FarmServer/app/views/plants/_form.html.erb
<%= form_for(@plant) do |f| %>
  <% if @plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
      <% @plant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :field_id %><br />
    <%= f.number_field :field_id %>
  </div>
  <div class="field">
    <%= f.label :x %><br />
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br />
    <%= f.number_field :y %>
  </div>
  <div class="field">
    <%= f.label :element_type_id %><br />
    <%= f.number_field :element_type_id %>
  </div>
  <div class="field">
    <%= f.label :growth_stage_id %><br />
    <%= f.number_field :growth_stage_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FarmServer/app/views/plants/edit.html.erb
<h1>Editing plant</h1>

<%= render 'form' %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

FarmServer/app/views/plants/index.html.erb
<h1>Listing plants</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Field</th>
    <th>X</th>
    <th>Y</th>
    <th>Type</th>
    <th>Process</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @plants.each do |plant| %>
  <tr>
    <td><%= plant.id %></td>
    <td><%= plant.field_id %></td>
    <td><%= plant.x %></td>
    <td><%= plant.y %></td>
    <td><%= plant.element_type_id %></td>
    <td><%= plant.growth_stage_id %></td>
    <td><%= link_to 'Show', plant %></td>
    <td><%= link_to 'Edit', edit_plant_path(plant) %></td>
    <td><%= link_to 'Destroy', plant, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Plant', new_plant_path %>

FarmServer/app/views/plants/new.html.erb
<h1>New plant</h1>

<%= render 'form' %>

<%= link_to 'Back', plants_path %>

FarmServer/app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @plant.id %>
</p>

<p>
  <b>Field:</b>
  <%= @plant.field_id %>
</p>

<p>
  <b>X:</b>
  <%= @plant.x %>
</p>

<p>
  <b>Y:</b>
  <%= @plant.y %>
</p>

<p>
  <b>Type:</b>
  <%= @plant.element_type_id %>
</p>

<p>
  <b>Process:</b>
  <%= @plant.growth_stage_id %>
</p>


<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>