FarmServer/config/routes.rb
FarmServer::Application.routes.draw do

  resources :element_types, :only => [:index]
  resources :elements, :only => [:index]
  resources :sessions, :only => [:create, :destroy]
  resources :plants, :only => [:index, :create]

=begin
  resources :plants do
    get 'growth_all', :on => collection
  end

  resources :picture do
    get 'download', :on => collection
  end
=end

  match 'plants/growth_all' => 'plants#growth_all'
  match 'plants/:id' => 'plants#destroy'

end

FarmServer/app/controllers/element_types_controller.rb
require "builder"
class ElementTypesController < ApplicationController
  # GET /element_types
  # GET /element_types.json
  def index
    begin
      @element_types = ElementType.select("id, name")

      doc = Builder::XmlMarkup.new(:target => out_string = "", :indent => 1)
      doc.Types{
        @element_types.each{ |type|
          doc.Type(type.attributes)
        }
      }

      render xml: out_string
    rescue Exception => exc
      render xml: error(exc)
    end
  end

  # GET /element_types/1
  # GET /element_types/1.json
  def show
    @element_type = ElementType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @element_type }
    end
  end

  # GET /element_types/new
  # GET /element_types/new.json
  def new
    @element_type = ElementType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @element_type }
    end
  end

  # GET /element_types/1/edit
  def edit
    @element_type = ElementType.find(params[:id])
  end

  # POST /element_types
  # POST /element_types.json
  def create
    @element_type = ElementType.new(params[:element_type])

    respond_to do |format|
      if @element_type.save
        format.html { redirect_to @element_type, notice: 'Element type was successfully created.' }
        format.json { render json: @element_type, status: :created, location: @element_type }
      else
        format.html { render action: "new" }
        format.json { render json: @element_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /element_types/1
  # PUT /element_types/1.json
  def update
    @element_type = ElementType.find(params[:id])

    respond_to do |format|
      if @element_type.update_attributes(params[:element_type])
        format.html { redirect_to @element_type, notice: 'Element type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @element_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /element_types/1
  # DELETE /element_types/1.json
  def destroy
    @element_type = ElementType.find(params[:id])
    @element_type.destroy

    respond_to do |format|
      format.html { redirect_to element_types_url }
      format.json { head :ok }
    end
  end
end

FarmServer/app/helpers/element_types_helper.rb
module ElementTypesHelper
end

FarmServer/app/views/element_types/_form.html.erb
<%= form_for(@element_type) do |f| %>
  <% if @element_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element_type.errors.count, "error") %> prohibited this element_type from being saved:</h2>

      <ul>
      <% @element_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FarmServer/app/views/element_types/edit.html.erb
<h1>Editing element_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @element_type %> |
<%= link_to 'Back', element_types_path %>

FarmServer/app/views/element_types/index.html.erb
<h1>Listing element_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @element_types.each do |element_type| %>
  <tr>
    <td><%= element_type.name %></td>
    <td><%= link_to 'Show', element_type %></td>
    <td><%= link_to 'Edit', edit_element_type_path(element_type) %></td>
    <td><%= link_to 'Destroy', element_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Element type', new_element_type_path %>

FarmServer/app/views/element_types/new.html.erb
<h1>New element_type</h1>

<%= render 'form' %>

<%= link_to 'Back', element_types_path %>

FarmServer/app/views/element_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @element_type.name %>
</p>


<%= link_to 'Edit', edit_element_type_path(@element_type) %> |
<%= link_to 'Back', element_types_path %>