FarmServer/config/routes.rb
FarmServer::Application.routes.draw do

  resources :element_types, :only => [:index]
  resources :elements, :only => [:index]
  resources :sessions, :only => [:create, :destroy]
  resources :plants, :only => [:index, :create]

=begin
  resources :plants do
    get 'growth_all', :on => collection
  end

  resources :picture do
    get 'download', :on => collection
  end
=end

  match 'plants/growth_all' => 'plants#growth_all'
  match 'plants/:id' => 'plants#destroy'

end

FarmServer/app/models/element.rb
class Element < ActiveRecord::Base
  belongs_to :element_type
  belongs_to :growth_stage
end

FarmServer/app/models/element_type.rb
class ElementType < ActiveRecord::Base
  has_many :element
end

FarmServer/app/controllers/elements_controller.rb
class ElementsController < ApplicationController
  # GET /elements
  # GET /elements.json
  def index
    begin
      @elements = Element.select("id, element_type_id, growth_id, url_pic")

      doc = Builder::XmlMarkup.new(:target => out_string = "", :indent => 1)
      doc.Elements{
        @elements.each{ |element|
          doc.Type(element.attributes)
        }
      }

      render xml: out_string
    rescue Exception => exc
      render xml: error(exc)
    end
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
    @element = Element.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @element }
    end
  end

  # GET /elements/new
  # GET /elements/new.json
  def new
    @element = Element.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @element }
    end
  end

  # GET /elements/1/edit
  def edit
    @element = Element.find(params[:id])
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(params[:element])

    respond_to do |format|
      if @element.save
        format.html { redirect_to @element, notice: 'Element was successfully created.' }
        format.json { render json: @element, status: :created, location: @element }
      else
        format.html { render action: "new" }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elements/1
  # PUT /elements/1.json
  def update
    @element = Element.find(params[:id])

    respond_to do |format|
      if @element.update_attributes(params[:element])
        format.html { redirect_to @element, notice: 'Element was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element = Element.find(params[:id])
    @element.destroy

    respond_to do |format|
      format.html { redirect_to elements_url }
      format.json { head :ok }
    end
  end
end

FarmServer/app/helpers/elements_helper.rb
module ElementsHelper
end

FarmServer/app/views/elements/_form.html.erb
<%= form_for(@element) do |f| %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label :element_type_id %><br />
  <%= f.text_field :element_type_id %>
  </div>
  <div class="field">
    <%= f.label :growth_id %><br />
    <%= f.text_field :growth_id %>
  </div>
  <div class="field">
    <%= f.label :url_pic %><br />
    <%= f.text_field :url_pic %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

FarmServer/app/views/elements/edit.html.erb
<h1>Editing element</h1>

<%= render 'form' %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

FarmServer/app/views/elements/index.html.erb
<h1>Listing elements</h1>

<table>
  <tr>
    <th>Url picture</th>
    <th>Element_type_id</th>
    <th>Growth_id</th>
    <th></th>
  </tr>

<% @elements.each do |element| %>
  <tr>
    <td><%= element.url_pic %></td>
    <td><%= element.element_type_id %></td>
    <td><%= element.growth_id %></td>
    <td><%= link_to 'Show', element %></td>
    <td><%= link_to 'Edit', edit_element_path(element) %></td>
    <td><%= link_to 'Destroy', element, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Element', new_element_path %>

FarmServer/app/views/elements/new.html.erb
<h1>New element</h1>

<%= render 'form' %>

<%= link_to 'Back', elements_path %>

FarmServer/app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url picture:</b><%= @element.url_pic %>
  <b>Element_type_id</b><%= @element.element_type_id %>
  <b>Growth_id</b> <%= @element.growth_id %>
</p>


<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>